"""Encrypt-at-rest helper for OAuth tokens stored in the control DB.

Every connector's refresh/access token is encrypted with Fernet (AES-128-CBC
+ HMAC) before it ever touches the database, using GANAK_TOKEN_ENCRYPTION_KEY.
Generate one with:
  python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

Local dev without the env var set still works (a key is derived from
AUTH_SECRET so nothing crashes), but production MUST set a real generated
key -- falling back silently there would mean tokens are only as safe as the
auth secret, and the two should not be the same secret.
"""
import base64
import hashlib

from cryptography.fernet import Fernet, InvalidToken

from .config import get_settings

settings = get_settings()
_fernet: "Fernet | None" = None


def _derive_key_from(secret: str) -> bytes:
    # Fernet needs a url-safe base64-encoded 32-byte key.
    digest = hashlib.sha256(secret.encode()).digest()
    return base64.urlsafe_b64encode(digest)


def _get_fernet() -> Fernet:
    global _fernet
    if _fernet is not None:
        return _fernet
    # Always derive a proper Fernet key from whatever secret material we have,
    # rather than assuming GANAK_TOKEN_ENCRYPTION_KEY is already a valid
    # urlsafe-base64 32-byte Fernet key -- a value auto-generated by the
    # hosting platform (e.g. Render's `generateValue: true`) is just a random
    # string, not necessarily Fernet-shaped, and Fernet(...) raises on
    # anything else. Deriving means any non-empty secret works safely.
    key_material = settings.GANAK_TOKEN_ENCRYPTION_KEY.strip() or (settings.AUTH_SECRET + "::token-encryption")
    _fernet = Fernet(_derive_key_from(key_material))
    return _fernet


def encrypt(plaintext: str) -> str:
    if not plaintext:
        return ""
    return _get_fernet().encrypt(plaintext.encode()).decode()


def decrypt(ciphertext: str) -> str:
    if not ciphertext:
        return ""
    try:
        return _get_fernet().decrypt(ciphertext.encode()).decode()
    except InvalidToken:
        return ""
